[package]
name = "union-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
axum-macros = "0.3.7"
serde_json = "1.0.97"
tokio = { version = "1.28.2", features = ["full"] }
